"""Central de avisos do lojista (admin-push.js, v3.4): público (todos/equipe/alunos/perfil/acesso/pessoas/pedido/etapa/interesse),
{nome}, link/imagem/validade, agendamento, prévia, teste no próprio aparelho, modelos (criar/editar/excluir), histórico (números, cancelar, usar de novo),
tela "Preparar" (o que falta no OneSignal) e o painel com o backend ANTIGO (3.2) seguindo no painel simples. Apps Script simulado (mock.py)."""
import sys, os, json
AQUI = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, AQUI)
os.makedirs(os.path.join(AQUI, 'saida'), exist_ok=True)
from mock import *
from playwright.sync_api import sync_playwright
AXE = open(os.path.join(AQUI, 'axe.min.js')).read()
BASE = os.environ.get("TK_BASE", "http://localhost:8765/")
SITE = "https://tenkitermodas.com.br/"
OK = []; BAD = []
def chk(n, c, e=""):
    (OK if c else BAD).append(n); print(("  ✔ " if c else "  ✘ ") + n + ((" — " + str(e)) if (e and not c) else ""))
def axe(pg, label):
    pg.evaluate(AXE)
    r = pg.evaluate("async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa','best-practice']}});return r.violations.map(v=>({id:v.id,impact:v.impact,n:v.nodes.length,ex:v.nodes.slice(0,3).map(n=>n.target.join(' ')+' :: '+(n.failureSummary||'').split('\\n')[1])}))}")
    chk("axe — " + label, not r, "; ".join("%s×%d %s" % (v['id'], v['n'], v['ex'][:2]) for v in r))
DIALOGOS = []
def dialogo(d):
    DIALOGOS.append((d.type, d.message)); d.accept()

def pagina(ctx, erros):
    pg = ctx.new_page()
    pg.on("pageerror", lambda e: erros.append(str(e)))
    pg.on("dialog", dialogo)
    return pg
def abrir_central(pg):
    if pg.locator("#details-ferramentas[open]").count() == 0:
        pg.click("#details-ferramentas > summary"); pg.wait_for_timeout(250)
    pg.click("#btn-abrir-push"); pg.wait_for_timeout(900)
def aba(pg, nome): pg.click("#av-aba-" + nome); pg.wait_for_timeout(700)
def corpo(pg): return pg.inner_text("#av-corpo")

with sync_playwright() as p:
    b = p.chromium.launch(args=["--no-sandbox"])
    ctx = b.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True, service_workers="block")
    ctx.add_init_script(SESSION)
    log = []
    st = install(ctx, log=log, versao="3.3")
    erros = []
    pg = pagina(ctx, erros)
    pg.goto(BASE + "admin.html"); pg.wait_for_timeout(2600)

    print("== Abrir a Central ==")
    abrir_central(pg)
    chk("o botão 'Enviar Notificação' abre a CENTRAL (não o painel simples)", pg.locator("#overlay-avisos.aberto").count() == 1 and pg.locator("#painel-push").is_hidden())
    chk("4 abas: Enviar, Histórico, Modelos, Preparar", pg.locator("#overlay-avisos [role=tab]").count() == 4)
    chk("abre na aba Enviar com os 3 blocos", pg.locator("#av-publico").is_visible() and pg.locator("#av-titulo-in").is_visible() and pg.locator("#av-enviar").is_visible())
    opts = pg.eval_on_selector_all("#av-publico option", "e=>e.map(o=>o.value)")
    chk("públicos: todos, app, interesse, grupos, perfil, acesso, pessoas, pedido, etapa", all(x in opts for x in ["todos", "app", "interesse", "g:equipe", "g:alunos", "g:portal", "g:clientes", "g:contas", "perfil", "acesso", "pessoas", "pedido", "pedidos"]), opts)
    chk("sem segmento do OneSignal quando só existe o padrão", "segmento" not in opts, opts)
    axe(pg, "Central — aba Enviar")

    print("== Prévia do público ==")
    pg.select_option("#av-publico", "g:alunos"); pg.wait_for_timeout(900)
    chk("prévia conta as pessoas do grupo (2) e mostra nomes", "2 pessoa(s)" in pg.inner_text("#av-previa") and "Bia Aluna" in pg.inner_text("#av-previa"), pg.inner_text("#av-previa"))
    pg.select_option("#av-publico", "todos"); pg.wait_for_timeout(900)
    chk("'todos' explica que o número exato vem depois do envio", "Quem já ativou" in pg.inner_text("#av-previa"), pg.inner_text("#av-previa"))

    print("== Título, mensagem, {nome}, prévia da notificação ==")
    pg.fill("#av-titulo-in", "Promoção de sábado 🎉")
    pg.fill("#av-msg-in", "Oi, ")
    pg.focus("#av-msg-in"); pg.keyboard.press("End"); pg.click("#av-ins-nome")
    chk("botão 'Inserir {nome}' põe {nome} na mensagem", "{nome}" in pg.input_value("#av-msg-in"), pg.input_value("#av-msg-in"))
    pg.fill("#av-msg-in", "Oi, {nome}! 20% off.")
    pn = pg.inner_text("#av-notif")
    chk("'Como vai aparecer' troca {nome} por um exemplo e mostra título e mensagem", "Promoção de sábado" in pn and "Oi, Maria! 20% off." in pn, pn)
    chk("contadores de caracteres", pg.inner_text("#av-c-t") == str(pg.evaluate("document.getElementById('av-titulo-in').value.length")) and pg.inner_text("#av-c-m") == str(len("Oi, {nome}! 20% off.")), (pg.inner_text("#av-c-t"), pg.inner_text("#av-c-m")))
    pg.fill("#av-img-in", "https://res.cloudinary.com/z/image/upload/v1/x1.jpg"); pg.wait_for_timeout(200)
    chk("imagem https aparece na pré-visualização", pg.locator("#av-notif img.av-img").count() == 1)

    print("== Validações ==")
    pg.fill("#av-url-in", "http://inseguro.com")
    pg.click("#av-enviar"); pg.wait_for_timeout(300)
    chk("link sem https é recusado com texto claro", "https://" in pg.inner_text("#av-resultado") and "ultimo_push" not in st, pg.inner_text("#av-resultado"))
    pg.fill("#av-url-in", SITE); pg.fill("#av-img-in", "ftp://x/y.jpg")
    pg.click("#av-enviar"); pg.wait_for_timeout(300)
    chk("imagem sem https é recusada", "imagem" in pg.inner_text("#av-resultado").lower() and "ultimo_push" not in st)
    pg.fill("#av-img-in", ""); pg.fill("#av-titulo-in", "")
    pg.click("#av-enviar"); pg.wait_for_timeout(300)
    chk("sem título: pede para preencher", "título" in pg.inner_text("#av-resultado").lower() and "ultimo_push" not in st)
    pg.fill("#av-titulo-in", "Promoção de sábado 🎉")

    print("== Enviar para um GRUPO (alunos) ==")
    pg.select_option("#av-publico", "g:alunos"); pg.wait_for_timeout(700)
    pg.select_option("#av-ttl", "24")
    DIALOGOS.clear(); log.clear()
    pg.click("#av-enviar"); pg.wait_for_timeout(1100)
    u = st.get("ultimo_push", {})
    chk("pediu confirmação citando o público", DIALOGOS and DIALOGOS[0][0] == "confirm" and "Promoção de sábado" in DIALOGOS[0][1] and "pessoa(s)" in DIALOGOS[0][1], DIALOGOS)
    chk("enviou audiência 'grupo alunos' com título, mensagem e link", u.get("audiencia") == {"tipo": "grupo", "grupo": "alunos"} and u.get("titulo") == "Promoção de sábado 🎉" and u.get("mensagem") == "Oi, {nome}! 20% off." and u.get("url") == SITE, u)
    chk("validade de 24 h vai junto (ttlHoras)", u.get("ttlHoras") == 24, u)
    chk("sem agendamento, não manda agendarEm", "agendarEm" not in u)
    chk("o envio leva a sessão (pin/sessao/whatsapp) como as outras ações do painel", log and log[-1].get("whatsapp") == "88999999999" and log[-1].get("sessao"))
    chk("resultado verde com ✅ e sem JSON cru", "✅" in pg.inner_text("#av-resultado") and "{" not in pg.inner_text("#av-resultado").replace("{nome}", ""), pg.inner_text("#av-resultado"))

    print("== Aviso de quem ficou sem aparelho ==")
    st["pushcfg"]["semAviso"] = ["Caio Cliente"]
    pg.click("#av-enviar"); pg.wait_for_timeout(1000)
    chk("lista quem NÃO recebeu por não ter ativado os avisos", "Caio Cliente" in pg.inner_text("#av-resultado") and "não receberam" in pg.inner_text("#av-resultado"), pg.inner_text("#av-resultado"))
    st["pushcfg"]["semAviso"] = []

    print("== Por interesse / perfil / acesso ==")
    pg.select_option("#av-publico", "interesse"); pg.wait_for_timeout(500)
    chk("interesses vêm dos gêneros da loja", pg.locator("#av-sub-interesses .chip").count() == 2)
    pg.click("#av-enviar"); pg.wait_for_timeout(300)
    chk("interesse sem marcar: pede para marcar", "interesse" in pg.inner_text("#av-resultado").lower() and len(st["avisos"]) == 2)
    pg.click('#av-sub-interesses [data-int="infantil-menina"]'); pg.wait_for_timeout(300)
    chk("chip de interesse fica marcado (aria-pressed)", pg.get_attribute('#av-sub-interesses [data-int="infantil-menina"]', "aria-pressed") == "true")
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("enviou interesse com chave e rótulo", st["ultimo_push"]["audiencia"] == {"tipo": "interesse", "chaves": ["infantil-menina"], "rotulos": ["Infantil Menina"]}, st["ultimo_push"]["audiencia"])
    pg.select_option("#av-publico", "perfil"); pg.wait_for_timeout(500)
    pg.check('#av-sub [data-perfil="Aluno"]'); pg.check('#av-sub [data-perfil="Cliente"]'); pg.wait_for_timeout(700)
    chk("prévia do perfil", "2 pessoa(s)" in pg.inner_text("#av-previa"), pg.inner_text("#av-previa"))
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("enviou perfis escolhidos", st["ultimo_push"]["audiencia"] == {"tipo": "perfil", "perfis": ["Aluno", "Cliente"]}, st["ultimo_push"]["audiencia"])
    pg.select_option("#av-publico", "acesso"); pg.wait_for_timeout(500)
    pg.click("#av-enviar"); pg.wait_for_timeout(300)
    chk("acesso sem marcar: pede para marcar", "acesso" in pg.inner_text("#av-resultado").lower())
    pg.check('#av-sub [data-acesso="portal"]'); pg.check('#av-sub [value="todas"]'); pg.wait_for_timeout(600)
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("enviou acesso com o modo 'todas'", st["ultimo_push"]["audiencia"] == {"tipo": "acesso", "chaves": ["portal"], "modo": "todas"}, st["ultimo_push"]["audiencia"])

    print("== Pessoas específicas ==")
    pg.select_option("#av-publico", "pessoas"); pg.wait_for_timeout(500)
    pg.click("#av-enviar"); pg.wait_for_timeout(300)
    chk("sem ninguém escolhido: avisa", "pessoa" in pg.inner_text("#av-resultado").lower())
    pg.fill("#av-busca-pessoa", "bia"); pg.wait_for_timeout(900)
    chk("busca por nome mostra a pessoa com telefone mascarado", "Bia Aluna" in pg.inner_text("#av-achadas") and "9****-0005" in pg.inner_text("#av-achadas"), pg.inner_text("#av-achadas"))
    pg.click("[data-add-pessoa]"); pg.wait_for_timeout(500)
    chk("pessoa vira um 'chip' removível", pg.locator("#av-escolhidas [data-rem-pessoa]").count() == 1)
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("enviou para a pessoa escolhida (id opaco, nunca telefone)", st["ultimo_push"]["audiencia"] == {"tipo": "pessoas", "ids": ["tkaluna0000000000000000000000001"]} and "9" not in json.dumps(st["ultimo_push"]["audiencia"]).replace("tkaluna0000000000000000000000001", ""), st["ultimo_push"]["audiencia"])

    print("== Pedido e etapa do pedido ==")
    pg.select_option("#av-publico", "pedido"); pg.wait_for_timeout(500)
    pg.click("#av-enviar"); pg.wait_for_timeout(500)
    chk("pedido sem código: mensagem clara", "pedido" in pg.inner_text("#av-resultado").lower() or "código" in pg.inner_text("#av-previa").lower(), pg.inner_text("#av-resultado"))
    pg.fill("#av-cod-pedido", "PED-0001"); pg.wait_for_timeout(700)
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("enviou para o cliente do pedido", st["ultimo_push"]["audiencia"] == {"tipo": "pedido", "codigo": "PED-0001"}, st["ultimo_push"]["audiencia"])
    pg.select_option("#av-publico", "pedidos"); pg.wait_for_timeout(500)
    pg.select_option("#av-etapa", "pronto")
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("enviou para quem tem pedido na etapa 'pronto'", st["ultimo_push"]["audiencia"] == {"tipo": "pedidos", "status": "pronto"}, st["ultimo_push"]["audiencia"])

    print("== Agendamento ==")
    pg.select_option("#av-publico", "app"); pg.wait_for_timeout(500)
    pg.check('input[name="av-quando"][value="agendar"]'); pg.wait_for_timeout(300)
    chk("campo de dia/hora aparece e já vem preenchido (daqui a 1 h)", pg.locator("#av-data").is_visible() and len(pg.input_value("#av-data")) == 16, pg.input_value("#av-data"))
    pg.fill("#av-data", "2026-10-11T09:00")
    pg.click("#av-enviar"); pg.wait_for_timeout(900)
    chk("agendamento vai como data ISO e o resultado diz 'agendado'", st["ultimo_push"].get("agendarEm", "").startswith("2026-10-11T") and "agendado" in pg.inner_text("#av-resultado").lower(), (st["ultimo_push"].get("agendarEm"), pg.inner_text("#av-resultado")))
    pg.check('input[name="av-quando"][value="agora"]')

    print("== Teste no meu aparelho ==")
    log.clear()
    pg.click("#av-teste"); pg.wait_for_timeout(1200)
    chk("pediu o pushId pela sessão (sem senha)", any(x.get("action") == "pushIdentidade" and not x.get("pin") and x.get("sessao") for x in log))
    chk("teste vai SÓ para o próprio aparelho com '[Teste]' no título", st["ultimo_push"]["audiencia"] == {"tipo": "pessoas", "ids": ["tkpush0000000000000000000000000"]} and st["ultimo_push"]["titulo"].startswith("[Teste]"), st["ultimo_push"])

    print("== Erro do servidor em texto legível ==")
    st["pushcfg"]["falhar"] = "OneSignal recusou: a plataforma Web ainda não foi configurada."
    pg.select_option("#av-publico", "todos"); pg.wait_for_timeout(500)
    pg.click("#av-enviar"); pg.wait_for_timeout(1000)
    r = pg.inner_text("#av-resultado")
    chk("erro aparece como frase, nunca JSON", "❌" in r and "plataforma Web" in r and '"ok"' not in r and "{" not in r, r)
    st["pushcfg"].pop("falhar")

    print("== Peça como atalho ==")
    cod = st["produtos"][2]["Codigo"]
    pg.fill("#av-peca-in", cod); pg.dispatch_event("#av-peca-in", "change"); pg.wait_for_timeout(300)
    chk("escolher a peça põe o link curto dela", pg.input_value("#av-url-in").startswith(SITE + "p/" + cod), pg.input_value("#av-url-in"))

    print("== Modelos ==")
    aba(pg, "modelos")
    chk("lista os modelos salvos (2)", pg.locator("#md-lista li").count() == 2, corpo(pg))
    axe(pg, "Central — aba Modelos")
    pg.fill("#md-rotulo", "Liquidação"); pg.fill("#md-titulo", "Liquidação! 🔥"); pg.fill("#md-msg", "Tudo com desconto hoje.")
    pg.click("#md-salvar"); pg.wait_for_timeout(700)
    chk("criou um modelo novo", pg.locator("#md-lista li").count() == 3 and "Liquidação" in pg.inner_text("#md-lista"))
    pg.click('#md-lista [data-edit="2"]'); pg.wait_for_timeout(300)
    chk("editar carrega o modelo no formulário", pg.input_value("#md-titulo") == "Liquidação! 🔥")
    pg.fill("#md-titulo", "Liquidação total! 🔥"); pg.click("#md-salvar"); pg.wait_for_timeout(700)
    chk("salvou a edição", "Liquidação total" in pg.inner_text("#md-lista") and pg.locator("#md-lista li").count() == 3)
    pg.fill("#md-rotulo", "Ruim"); pg.fill("#md-titulo", "x"); pg.fill("#md-msg", ""); pg.click("#md-salvar"); pg.wait_for_timeout(500)
    chk("modelo incompleto: erro em frase", "obrigatórios" in pg.inner_text("#md-res"), pg.inner_text("#md-res"))
    DIALOGOS.clear()
    pg.click('#md-lista [data-del="2"]'); pg.wait_for_timeout(700)
    chk("excluir pede confirmação e remove", DIALOGOS and DIALOGOS[0][0] == "confirm" and pg.locator("#md-lista li").count() == 2)
    aba(pg, "enviar")
    pg.click('#av-modelos-rapidos [data-m="0"]'); pg.wait_for_timeout(200)
    chk("modelo rápido preenche título e mensagem na aba Enviar", "Promoção" in pg.input_value("#av-titulo-in") and "{nome}" in pg.input_value("#av-msg-in"))

    print("== Histórico ==")
    aba(pg, "historico")
    chk("histórico lista os avisos enviados com público e destinatários", pg.locator(".av-hist").count() >= 8 and "destinatário" in corpo(pg), pg.locator(".av-hist").count())
    axe(pg, "Central — aba Histórico")
    pg.locator("[data-num]").first.click(); pg.wait_for_timeout(800)
    chk("'Ver números' mostra entregues, cliques e falhas", "Entregues: 5" in corpo(pg) and "Cliques: 2" in corpo(pg) and "Falhas: 1" in corpo(pg), corpo(pg)[:300])
    chk("há aviso agendado com botão de cancelar", pg.locator("[data-canc]").count() >= 1)
    DIALOGOS.clear()
    pg.locator("[data-canc]").first.click(); pg.wait_for_timeout(1200)
    chk("cancelar agendamento confirma e marca como cancelado", DIALOGOS and DIALOGOS[0][0] == "confirm" and any(x["resultado"] == "cancelado" for x in st["push"]))
    pg.locator("[data-reusar]").first.click(); pg.wait_for_timeout(700)
    chk("'Usar de novo' volta à aba Enviar com o texto preenchido", pg.locator("#av-titulo-in").is_visible() and len(pg.input_value("#av-titulo-in")) > 3)

    print("== Preparar (o que falta) ==")
    st["pushcfg"]["web"] = False
    aba(pg, "preparar")
    t = corpo(pg)
    chk("mostra que a plataforma Web NÃO está pronta e os passos do OneSignal", "ainda não está configurado para Web push" in t and "Site URL" in t and "tenkitermodas.com.br" in t, t[:400])
    chk("chave configurada aparece como ok sem mostrar a chave", "ONESIGNAL" not in t.split("1. Chave")[1][:60] or "nunca aparece" in t)
    chk("aviso no topo da aba Enviar quando não está pronto", (aba(pg, "enviar") or True) and "ainda não estão prontos" in corpo(pg))
    aba(pg, "preparar")
    axe(pg, "Central — aba Preparar (não pronto)")
    st["pushcfg"]["web"] = True
    pg.click("#pr-verificar"); pg.wait_for_timeout(900)
    t = corpo(pg)
    chk("depois de configurar, 'Verificar de novo' mostra pronto", "pronto para entregar avisos" in t and "Site URL" not in t, t[:300])
    chk("contas por grupo", "equipe 2" in t and "alunos 3" in t and "clientes 2" in t, t)
    pg.uncheck("#pr-auto-novo"); pg.wait_for_timeout(700)
    chk("Admin total liga/desliga o aviso automático de pedido novo", st["pushcfg"]["novo"] is False and "Salvo" in pg.inner_text("#pr-res"))
    pg.check("#pr-auto-novo"); pg.wait_for_timeout(500)

    print("== Fechar ==")
    pg.click("#av-fechar"); pg.wait_for_timeout(500)
    chk("✕ fecha a Central", pg.locator("#overlay-avisos.aberto").count() == 0)
    abrir_central(pg)
    pg.keyboard.press("Escape"); pg.wait_for_timeout(500)
    chk("Esc fecha a Central", pg.locator("#overlay-avisos.aberto").count() == 0)
    chk("nenhum erro de JavaScript", not erros, erros[:3])
    ctx.close()

    print("== Sem 'Admin total': só mexe nos avisos automáticos quem pode ==")
    perms = [x for x in PERMS_ALL if x != "gerir_acessos"]
    ctx = b.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True, service_workers="block")
    ctx.add_init_script(SESSION)
    st2 = install(ctx, perms=perms, versao="3.3")
    pg = pagina(ctx, erros)
    pg.goto(BASE + "admin.html"); pg.wait_for_timeout(2600)
    abrir_central(pg); aba(pg, "preparar")
    chk("sem permissão, as caixinhas dos avisos automáticos ficam travadas e explica", pg.locator("#pr-auto-novo").is_disabled() and "Só o Admin total" in corpo(pg))
    ctx.close()

    print("== Backend ANTIGO (3.2): continua o painel simples ==")
    ctx = b.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True, service_workers="block")
    ctx.add_init_script(SESSION)
    install(ctx, versao="3.2")
    pg = pagina(ctx, erros)
    pg.goto(BASE + "admin.html"); pg.wait_for_timeout(2600)
    if pg.locator("#details-ferramentas[open]").count() == 0: pg.click("#details-ferramentas > summary"); pg.wait_for_timeout(250)
    pg.click("#btn-abrir-push"); pg.wait_for_timeout(600)
    chk("sem pushCompleto o painel simples abre e a Central nem é criada", pg.locator("#painel-push").is_visible() and pg.locator("#overlay-avisos").count() == 0)
    chk("nenhum erro de JavaScript (backend antigo)", not erros, erros[:3])
    b.close()

print("\nFALHAS=%d %s" % (len(BAD), BAD))
sys.exit(1 if BAD else 0)
